/**
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes.gramaticajmeter;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Architecture Results</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link co.edu.uniandes.gramaticajmeter.ArchitectureResults#getArchitecture <em>Architecture</em>}</li>
 *   <li>{@link co.edu.uniandes.gramaticajmeter.ArchitectureResults#getHeader <em>Header</em>}</li>
 *   <li>{@link co.edu.uniandes.gramaticajmeter.ArchitectureResults#getResults <em>Results</em>}</li>
 *   <li>{@link co.edu.uniandes.gramaticajmeter.ArchitectureResults#getHeaderJMeter <em>Header JMeter</em>}</li>
 *   <li>{@link co.edu.uniandes.gramaticajmeter.ArchitectureResults#getResultsJMeter <em>Results JMeter</em>}</li>
 * </ul>
 * </p>
 *
 * @see co.edu.uniandes.gramaticajmeter.GramaticajmeterPackage#getArchitectureResults()
 * @model
 * @generated
 */
public interface ArchitectureResults extends EObject
{
  /**
   * Returns the value of the '<em><b>Architecture</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Architecture</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Architecture</em>' attribute.
   * @see #setArchitecture(String)
   * @see co.edu.uniandes.gramaticajmeter.GramaticajmeterPackage#getArchitectureResults_Architecture()
   * @model
   * @generated
   */
  String getArchitecture();

  /**
   * Sets the value of the '{@link co.edu.uniandes.gramaticajmeter.ArchitectureResults#getArchitecture <em>Architecture</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Architecture</em>' attribute.
   * @see #getArchitecture()
   * @generated
   */
  void setArchitecture(String value);

  /**
   * Returns the value of the '<em><b>Header</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Header</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header</em>' containment reference.
   * @see #setHeader(Header)
   * @see co.edu.uniandes.gramaticajmeter.GramaticajmeterPackage#getArchitectureResults_Header()
   * @model containment="true"
   * @generated
   */
  Header getHeader();

  /**
   * Sets the value of the '{@link co.edu.uniandes.gramaticajmeter.ArchitectureResults#getHeader <em>Header</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Header</em>' containment reference.
   * @see #getHeader()
   * @generated
   */
  void setHeader(Header value);

  /**
   * Returns the value of the '<em><b>Results</b></em>' containment reference list.
   * The list contents are of type {@link co.edu.uniandes.gramaticajmeter.Results}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Results</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Results</em>' containment reference list.
   * @see co.edu.uniandes.gramaticajmeter.GramaticajmeterPackage#getArchitectureResults_Results()
   * @model containment="true"
   * @generated
   */
  EList<Results> getResults();

  /**
   * Returns the value of the '<em><b>Header JMeter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Header JMeter</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header JMeter</em>' containment reference.
   * @see #setHeaderJMeter(HeaderJMeter)
   * @see co.edu.uniandes.gramaticajmeter.GramaticajmeterPackage#getArchitectureResults_HeaderJMeter()
   * @model containment="true"
   * @generated
   */
  HeaderJMeter getHeaderJMeter();

  /**
   * Sets the value of the '{@link co.edu.uniandes.gramaticajmeter.ArchitectureResults#getHeaderJMeter <em>Header JMeter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Header JMeter</em>' containment reference.
   * @see #getHeaderJMeter()
   * @generated
   */
  void setHeaderJMeter(HeaderJMeter value);

  /**
   * Returns the value of the '<em><b>Results JMeter</b></em>' containment reference list.
   * The list contents are of type {@link co.edu.uniandes.gramaticajmeter.Results}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Results JMeter</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Results JMeter</em>' containment reference list.
   * @see co.edu.uniandes.gramaticajmeter.GramaticajmeterPackage#getArchitectureResults_ResultsJMeter()
   * @model containment="true"
   * @generated
   */
  EList<Results> getResultsJMeter();

} // ArchitectureResults
