/**
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes.gramaticajmeter;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see co.edu.uniandes.gramaticajmeter.GramaticajmeterFactory
 * @model kind="package"
 * @generated
 */
public interface GramaticajmeterPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "gramaticajmeter";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.edu.co/uniandes/Gramaticajmeter";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "gramaticajmeter";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GramaticajmeterPackage eINSTANCE = co.edu.uniandes.gramaticajmeter.impl.GramaticajmeterPackageImpl.init();

  /**
   * The meta object id for the '{@link co.edu.uniandes.gramaticajmeter.impl.JMeterImpl <em>JMeter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.gramaticajmeter.impl.JMeterImpl
   * @see co.edu.uniandes.gramaticajmeter.impl.GramaticajmeterPackageImpl#getJMeter()
   * @generated
   */
  int JMETER = 0;

  /**
   * The feature id for the '<em><b>Architecture Results</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JMETER__ARCHITECTURE_RESULTS = 0;

  /**
   * The number of structural features of the '<em>JMeter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JMETER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link co.edu.uniandes.gramaticajmeter.impl.ArchitectureResultsImpl <em>Architecture Results</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.gramaticajmeter.impl.ArchitectureResultsImpl
   * @see co.edu.uniandes.gramaticajmeter.impl.GramaticajmeterPackageImpl#getArchitectureResults()
   * @generated
   */
  int ARCHITECTURE_RESULTS = 1;

  /**
   * The feature id for the '<em><b>Architecture</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHITECTURE_RESULTS__ARCHITECTURE = 0;

  /**
   * The feature id for the '<em><b>Header</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHITECTURE_RESULTS__HEADER = 1;

  /**
   * The feature id for the '<em><b>Results</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHITECTURE_RESULTS__RESULTS = 2;

  /**
   * The feature id for the '<em><b>Header JMeter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHITECTURE_RESULTS__HEADER_JMETER = 3;

  /**
   * The feature id for the '<em><b>Results JMeter</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHITECTURE_RESULTS__RESULTS_JMETER = 4;

  /**
   * The number of structural features of the '<em>Architecture Results</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHITECTURE_RESULTS_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link co.edu.uniandes.gramaticajmeter.impl.HeaderImpl <em>Header</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.gramaticajmeter.impl.HeaderImpl
   * @see co.edu.uniandes.gramaticajmeter.impl.GramaticajmeterPackageImpl#getHeader()
   * @generated
   */
  int HEADER = 2;

  /**
   * The feature id for the '<em><b>Header</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER__HEADER = 0;

  /**
   * The number of structural features of the '<em>Header</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link co.edu.uniandes.gramaticajmeter.impl.ResultsImpl <em>Results</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.gramaticajmeter.impl.ResultsImpl
   * @see co.edu.uniandes.gramaticajmeter.impl.GramaticajmeterPackageImpl#getResults()
   * @generated
   */
  int RESULTS = 3;

  /**
   * The feature id for the '<em><b>Result</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULTS__RESULT = 0;

  /**
   * The number of structural features of the '<em>Results</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link co.edu.uniandes.gramaticajmeter.impl.ResultImpl <em>Result</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.gramaticajmeter.impl.ResultImpl
   * @see co.edu.uniandes.gramaticajmeter.impl.GramaticajmeterPackageImpl#getResult()
   * @generated
   */
  int RESULT = 4;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULT__VALUE = 0;

  /**
   * The number of structural features of the '<em>Result</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link co.edu.uniandes.gramaticajmeter.impl.HeaderJMeterImpl <em>Header JMeter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.gramaticajmeter.impl.HeaderJMeterImpl
   * @see co.edu.uniandes.gramaticajmeter.impl.GramaticajmeterPackageImpl#getHeaderJMeter()
   * @generated
   */
  int HEADER_JMETER = 5;

  /**
   * The feature id for the '<em><b>Header</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER_JMETER__HEADER = 0;

  /**
   * The number of structural features of the '<em>Header JMeter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER_JMETER_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link co.edu.uniandes.gramaticajmeter.JMeter <em>JMeter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JMeter</em>'.
   * @see co.edu.uniandes.gramaticajmeter.JMeter
   * @generated
   */
  EClass getJMeter();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.uniandes.gramaticajmeter.JMeter#getArchitectureResults <em>Architecture Results</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Architecture Results</em>'.
   * @see co.edu.uniandes.gramaticajmeter.JMeter#getArchitectureResults()
   * @see #getJMeter()
   * @generated
   */
  EReference getJMeter_ArchitectureResults();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.gramaticajmeter.ArchitectureResults <em>Architecture Results</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Architecture Results</em>'.
   * @see co.edu.uniandes.gramaticajmeter.ArchitectureResults
   * @generated
   */
  EClass getArchitectureResults();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.gramaticajmeter.ArchitectureResults#getArchitecture <em>Architecture</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Architecture</em>'.
   * @see co.edu.uniandes.gramaticajmeter.ArchitectureResults#getArchitecture()
   * @see #getArchitectureResults()
   * @generated
   */
  EAttribute getArchitectureResults_Architecture();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.uniandes.gramaticajmeter.ArchitectureResults#getHeader <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Header</em>'.
   * @see co.edu.uniandes.gramaticajmeter.ArchitectureResults#getHeader()
   * @see #getArchitectureResults()
   * @generated
   */
  EReference getArchitectureResults_Header();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.uniandes.gramaticajmeter.ArchitectureResults#getResults <em>Results</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Results</em>'.
   * @see co.edu.uniandes.gramaticajmeter.ArchitectureResults#getResults()
   * @see #getArchitectureResults()
   * @generated
   */
  EReference getArchitectureResults_Results();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.uniandes.gramaticajmeter.ArchitectureResults#getHeaderJMeter <em>Header JMeter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Header JMeter</em>'.
   * @see co.edu.uniandes.gramaticajmeter.ArchitectureResults#getHeaderJMeter()
   * @see #getArchitectureResults()
   * @generated
   */
  EReference getArchitectureResults_HeaderJMeter();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.uniandes.gramaticajmeter.ArchitectureResults#getResultsJMeter <em>Results JMeter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Results JMeter</em>'.
   * @see co.edu.uniandes.gramaticajmeter.ArchitectureResults#getResultsJMeter()
   * @see #getArchitectureResults()
   * @generated
   */
  EReference getArchitectureResults_ResultsJMeter();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.gramaticajmeter.Header <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Header</em>'.
   * @see co.edu.uniandes.gramaticajmeter.Header
   * @generated
   */
  EClass getHeader();

  /**
   * Returns the meta object for the attribute list '{@link co.edu.uniandes.gramaticajmeter.Header#getHeader <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Header</em>'.
   * @see co.edu.uniandes.gramaticajmeter.Header#getHeader()
   * @see #getHeader()
   * @generated
   */
  EAttribute getHeader_Header();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.gramaticajmeter.Results <em>Results</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Results</em>'.
   * @see co.edu.uniandes.gramaticajmeter.Results
   * @generated
   */
  EClass getResults();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.uniandes.gramaticajmeter.Results#getResult <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Result</em>'.
   * @see co.edu.uniandes.gramaticajmeter.Results#getResult()
   * @see #getResults()
   * @generated
   */
  EReference getResults_Result();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.gramaticajmeter.Result <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Result</em>'.
   * @see co.edu.uniandes.gramaticajmeter.Result
   * @generated
   */
  EClass getResult();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.gramaticajmeter.Result#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see co.edu.uniandes.gramaticajmeter.Result#getValue()
   * @see #getResult()
   * @generated
   */
  EAttribute getResult_Value();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.gramaticajmeter.HeaderJMeter <em>Header JMeter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Header JMeter</em>'.
   * @see co.edu.uniandes.gramaticajmeter.HeaderJMeter
   * @generated
   */
  EClass getHeaderJMeter();

  /**
   * Returns the meta object for the attribute list '{@link co.edu.uniandes.gramaticajmeter.HeaderJMeter#getHeader <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Header</em>'.
   * @see co.edu.uniandes.gramaticajmeter.HeaderJMeter#getHeader()
   * @see #getHeaderJMeter()
   * @generated
   */
  EAttribute getHeaderJMeter_Header();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GramaticajmeterFactory getGramaticajmeterFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link co.edu.uniandes.gramaticajmeter.impl.JMeterImpl <em>JMeter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.gramaticajmeter.impl.JMeterImpl
     * @see co.edu.uniandes.gramaticajmeter.impl.GramaticajmeterPackageImpl#getJMeter()
     * @generated
     */
    EClass JMETER = eINSTANCE.getJMeter();

    /**
     * The meta object literal for the '<em><b>Architecture Results</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JMETER__ARCHITECTURE_RESULTS = eINSTANCE.getJMeter_ArchitectureResults();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.gramaticajmeter.impl.ArchitectureResultsImpl <em>Architecture Results</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.gramaticajmeter.impl.ArchitectureResultsImpl
     * @see co.edu.uniandes.gramaticajmeter.impl.GramaticajmeterPackageImpl#getArchitectureResults()
     * @generated
     */
    EClass ARCHITECTURE_RESULTS = eINSTANCE.getArchitectureResults();

    /**
     * The meta object literal for the '<em><b>Architecture</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARCHITECTURE_RESULTS__ARCHITECTURE = eINSTANCE.getArchitectureResults_Architecture();

    /**
     * The meta object literal for the '<em><b>Header</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARCHITECTURE_RESULTS__HEADER = eINSTANCE.getArchitectureResults_Header();

    /**
     * The meta object literal for the '<em><b>Results</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARCHITECTURE_RESULTS__RESULTS = eINSTANCE.getArchitectureResults_Results();

    /**
     * The meta object literal for the '<em><b>Header JMeter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARCHITECTURE_RESULTS__HEADER_JMETER = eINSTANCE.getArchitectureResults_HeaderJMeter();

    /**
     * The meta object literal for the '<em><b>Results JMeter</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARCHITECTURE_RESULTS__RESULTS_JMETER = eINSTANCE.getArchitectureResults_ResultsJMeter();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.gramaticajmeter.impl.HeaderImpl <em>Header</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.gramaticajmeter.impl.HeaderImpl
     * @see co.edu.uniandes.gramaticajmeter.impl.GramaticajmeterPackageImpl#getHeader()
     * @generated
     */
    EClass HEADER = eINSTANCE.getHeader();

    /**
     * The meta object literal for the '<em><b>Header</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEADER__HEADER = eINSTANCE.getHeader_Header();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.gramaticajmeter.impl.ResultsImpl <em>Results</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.gramaticajmeter.impl.ResultsImpl
     * @see co.edu.uniandes.gramaticajmeter.impl.GramaticajmeterPackageImpl#getResults()
     * @generated
     */
    EClass RESULTS = eINSTANCE.getResults();

    /**
     * The meta object literal for the '<em><b>Result</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESULTS__RESULT = eINSTANCE.getResults_Result();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.gramaticajmeter.impl.ResultImpl <em>Result</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.gramaticajmeter.impl.ResultImpl
     * @see co.edu.uniandes.gramaticajmeter.impl.GramaticajmeterPackageImpl#getResult()
     * @generated
     */
    EClass RESULT = eINSTANCE.getResult();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESULT__VALUE = eINSTANCE.getResult_Value();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.gramaticajmeter.impl.HeaderJMeterImpl <em>Header JMeter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.gramaticajmeter.impl.HeaderJMeterImpl
     * @see co.edu.uniandes.gramaticajmeter.impl.GramaticajmeterPackageImpl#getHeaderJMeter()
     * @generated
     */
    EClass HEADER_JMETER = eINSTANCE.getHeaderJMeter();

    /**
     * The meta object literal for the '<em><b>Header</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEADER_JMETER__HEADER = eINSTANCE.getHeaderJMeter_Header();

  }

} //GramaticajmeterPackage
