/**
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes.gramaticajmeter;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Header JMeter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link co.edu.uniandes.gramaticajmeter.HeaderJMeter#getHeader <em>Header</em>}</li>
 * </ul>
 * </p>
 *
 * @see co.edu.uniandes.gramaticajmeter.GramaticajmeterPackage#getHeaderJMeter()
 * @model
 * @generated
 */
public interface HeaderJMeter extends EObject
{
  /**
   * Returns the value of the '<em><b>Header</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Header</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header</em>' attribute list.
   * @see co.edu.uniandes.gramaticajmeter.GramaticajmeterPackage#getHeaderJMeter_Header()
   * @model unique="false"
   * @generated
   */
  EList<String> getHeader();

} // HeaderJMeter
