/**
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes.gramaticajmeter;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JMeter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link co.edu.uniandes.gramaticajmeter.JMeter#getArchitectureResults <em>Architecture Results</em>}</li>
 * </ul>
 * </p>
 *
 * @see co.edu.uniandes.gramaticajmeter.GramaticajmeterPackage#getJMeter()
 * @model
 * @generated
 */
public interface JMeter extends EObject
{
  /**
   * Returns the value of the '<em><b>Architecture Results</b></em>' containment reference list.
   * The list contents are of type {@link co.edu.uniandes.gramaticajmeter.ArchitectureResults}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Architecture Results</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Architecture Results</em>' containment reference list.
   * @see co.edu.uniandes.gramaticajmeter.GramaticajmeterPackage#getJMeter_ArchitectureResults()
   * @model containment="true"
   * @generated
   */
  EList<ArchitectureResults> getArchitectureResults();

} // JMeter
