/**
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes;

import co.edu.uniandes.GramaticajmeterStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GramaticajmeterStandaloneSetup extends GramaticajmeterStandaloneSetupGenerated {
  public static void doSetup() {
    GramaticajmeterStandaloneSetup _gramaticajmeterStandaloneSetup = new GramaticajmeterStandaloneSetup();
    _gramaticajmeterStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
