/**
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes.tests;

import co.edu.uniandes.gramaticajmeter.JMeter;
import co.edu.uniandes.tests.GramaticajmeterInjectorProvider;
import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(GramaticajmeterInjectorProvider.class)
@SuppressWarnings("all")
public class GramaticajmeterParsingTest {
  @Inject
  private ParseHelper<JMeter> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final JMeter result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
