/**
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes.scoping;

import co.edu.uniandes.scoping.AbstractGramaticajmeterScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class GramaticajmeterScopeProvider extends AbstractGramaticajmeterScopeProvider {
}
