/*
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GramaticajmeterStandaloneSetup extends GramaticajmeterStandaloneSetupGenerated {

	def static void doSetup() {
		new GramaticajmeterStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
