/*
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes.ui.tests;

import co.edu.uniandes.gramaticajmeter.ui.internal.GramaticajmeterActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class GramaticajmeterUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GramaticajmeterActivator.getInstance().getInjector("co.edu.uniandes.Gramaticajmeter");
	}

}
