/*
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes.parser.antlr;

import co.edu.uniandes.parser.antlr.internal.InternalGramaticajmeterParser;
import co.edu.uniandes.services.GramaticajmeterGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GramaticajmeterParser extends AbstractAntlrParser {

	@Inject
	private GramaticajmeterGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGramaticajmeterParser createParser(XtextTokenStream stream) {
		return new InternalGramaticajmeterParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "JMeter";
	}

	public GramaticajmeterGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GramaticajmeterGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
