/**
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes.ui;

import co.edu.uniandes.ui.AbstractGramaticajmeterUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GramaticajmeterUiModule extends AbstractGramaticajmeterUiModule {
  public GramaticajmeterUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
