/*
 * generated by Xtext 2.9.1
 */
package co.edu.uniandes.ui;

import co.edu.uniandes.gramaticajmeter.ui.internal.GramaticajmeterActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GramaticajmeterExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GramaticajmeterActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GramaticajmeterActivator.getInstance().getInjector(GramaticajmeterActivator.CO_EDU_UNIANDES_GRAMATICAJMETER);
	}
	
}
